apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - breakout
  - zula
  - headlamp
  - image-update-automation.yaml
  - zula-image-update-automation.yaml
  - zula-web-image-update-automation.yaml
