apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: zula-web-app
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(zula): update web-app image

        {{ range $_, $change := .Changed.Changes -}}
        - {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
    push:
      branch: main
  update:
    path: ./clusters/rpi/apps/zula
    strategy: Setters
