apiVersion: v1
kind: Namespace
metadata:
  name: cv-pdf
  labels:
    app.kubernetes.io/name: cv-pdf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-pdf
  namespace: cv-pdf
  labels:
    app.kubernetes.io/name: cv-pdf
    app.kubernetes.io/part-of: cv-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cv-pdf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cv-pdf
        app.kubernetes.io/part-of: cv-pdf
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: cv-pdf
          image: ghcr.io/bieniucieniu/cv-pdf:latest@sha256:052514ceb64e9647254d756f0ef3a09683cf0e36c2206ea54219c3f10c167ad2 # {"$imagepolicy": "flux-system:cv-pdf"}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cv-pdf
  namespace: cv-pdf
  labels:
    app.kubernetes.io/name: cv-pdf
    app.kubernetes.io/part-of: cv-pdf
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cv-pdf
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
