apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend-config.yaml
  - postgres-init.yaml
  - bitnami-helmrepository.yaml
  - postgres-helmrelease.yaml
  - minio-helmrelease.yaml
  - workload.yaml
  - web-workload.yaml
  - httproute.yaml
  - source.yaml
