apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: zula
  labels:
    app.kubernetes.io/name: zula-postgres
    app.kubernetes.io/part-of: zula
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  releaseName: postgres
  values:
    fullnameOverride: postgres
    architecture: standalone
    auth:
      enablePostgresUser: true
      username: postgres
      database: zula_dev
      existingSecret: zula
      secretKeys:
        adminPasswordKey: PG_PASSWORD
        userPasswordKey: PG_PASSWORD
    primary:
      initdb:
        scriptsConfigMap: postgres-init
      persistence:
        enabled: true
        size: 2Gi
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    metrics:
      enabled: false
