apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: zula-backend
  namespace: flux-system
spec:
  image: ghcr.io/bieniucieniu/zula-poc-1/backend
  interval: 1m
  secretRef:
    name: ghcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: zula-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zula-backend
  filterTags:
    pattern: ^latest$
  digestReflectionPolicy: Always
  interval: 5m
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: zula-web
  namespace: flux-system
spec:
  image: ghcr.io/bieniucieniu/zula-poc-1/web
  interval: 1m
  secretRef:
    name: ghcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: zula-web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zula-web
  filterTags:
    pattern: ^latest$
  digestReflectionPolicy: Always
  interval: 5m
  policy:
    alphabetical:
      order: asc
